"""
Telegram Notifier — Europe Job Hunter
Sends daily job digest to your Telegram.

Setup:
1. Message @BotFather on Telegram → /newbot → get TOKEN
2. Message @userinfobot → get your CHAT_ID
3. Add both to .env file
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JOBS_PATH = PROJECT_ROOT / "data" / "jobs_matched.json"
DEFAULT_PROFILE_PATH = PROJECT_ROOT / "data" / "profile.json"

load_dotenv(PROJECT_ROOT / ".env")


# ─── Telegram API ─────────────────────────────────────────────────────────────

def send_message(text: str, parse_mode: str = "HTML") -> bool:
    """Send a message to Telegram."""
    token   = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")

    if not token or not chat_id:
        print("❌ TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID must be set in .env")
        return False

    url  = f"https://api.telegram.org/bot{token}/sendMessage"
    data = {
        "chat_id":    chat_id,
        "text":       text,
        "parse_mode": parse_mode,
        "disable_web_page_preview": True,
    }

    try:
        res = requests.post(url, json=data, timeout=10)
        res.raise_for_status()
        return True
    except requests.exceptions.RequestException as e:
        print(f"❌ Telegram send failed: {e}")
        return False


def test_connection() -> bool:
    """Test if Telegram bot is working."""
    return send_message("✅ <b>EuroJobs Bot</b> is connected!\n\nYou'll receive daily job digests here.")


# ─── Message Formatters ───────────────────────────────────────────────────────

def format_job(job: dict, rank: int) -> str:
    """Format a single job as a Telegram message block."""
    score   = job.get("match_score", 0)
    emoji   = "🟢" if score >= 75 else "🟡" if score >= 55 else "🟠"
    salary  = f"\n💰 {job['salary']}" if job.get("salary") else ""
    url     = job.get("url", "#")

    return (
        f"{rank}. {emoji} <b>{job['title']}</b>\n"
        f"   🏢 {job['company']} · 📍 {job['location']}\n"
        f"   📊 Match: <b>{score}%</b>{salary}\n"
        f"   🔗 <a href='{url}'>View Job</a>"
    )


def format_daily_digest(jobs: list[dict], profile_name: str = "You") -> list[str]:
    """
    Format jobs into a daily digest message.
    Splits into multiple messages if too long (Telegram limit: 4096 chars).
    """
    if not jobs:
        return [
            "😔 <b>No new job matches today.</b>\n\n"
            "The pipeline will run again tomorrow at 8:00 AM."
        ]

    date_str = datetime.now().strftime("%d %b %Y")

    # Header
    excellent = sum(1 for j in jobs if j.get("match_score", 0) >= 75)
    good      = sum(1 for j in jobs if 55 <= j.get("match_score", 0) < 75)

    header = (
        f"🌍 <b>EuroJobs Daily Digest</b>\n"
        f"📅 {date_str} · Hi {profile_name.split()[0]}!\n\n"
        f"📊 <b>Today's Matches:</b>\n"
        f"  🟢 Excellent (75%+): {excellent}\n"
        f"  🟡 Good (55-75%): {good}\n"
        f"  📋 Total shown: {len(jobs)}\n"
        f"{'─' * 30}\n\n"
    )

    messages = []
    current  = header

    for i, job in enumerate(jobs, 1):
        job_block = format_job(job, i) + "\n\n"

        # Telegram message limit is 4096 chars
        if len(current) + len(job_block) > 3800:
            messages.append(current)
            current = job_block
        else:
            current += job_block

    # Footer
    footer = (
        f"{'─' * 30}\n"
        f"🤖 <i>Generated by EuroJobs Hunter</i>\n"
        f"💡 <i>Reply /help for commands</i>"
    )

    if len(current) + len(footer) > 3800:
        messages.append(current)
        messages.append(footer)
    else:
        messages.append(current + footer)

    return messages


# ─── Main Notifier ────────────────────────────────────────────────────────────

def send_daily_digest(
    jobs_path:    str = str(DEFAULT_JOBS_PATH),
    profile_path: str = str(DEFAULT_PROFILE_PATH),
    top_n:        int = 10,
    min_score:    float = 55.0,
) -> bool:
    """
    Send daily job digest to Telegram.

    Args:
        jobs_path:    Path to matched jobs JSON
        profile_path: Path to CV profile JSON
        top_n:        Number of top jobs to include
        min_score:    Minimum match score to include

    Returns:
        True if sent successfully
    """
    for path in [jobs_path, profile_path]:
        if not os.path.exists(path):
            print(f"❌ File not found: {path}")
            return False

    with open(jobs_path, encoding="utf-8")    as f: jobs    = json.load(f)
    with open(profile_path, encoding="utf-8") as f: profile = json.load(f)

    profile_name = profile.get("full_name", "there")

    # Filter and take top N
    eligible = [j for j in jobs if j.get("match_score", 0) >= min_score]
    top_jobs = sorted(eligible, key=lambda j: j["match_score"], reverse=True)[:top_n]

    print(f"\n📱 TELEGRAM NOTIFIER")
    print(f"👤 {profile_name}")
    print(f"📋 Sending {len(top_jobs)} jobs (score ≥ {min_score}%)")

    messages = format_daily_digest(top_jobs, profile_name)

    success_count = 0
    for i, msg in enumerate(messages, 1):
        print(f"  📤 Sending message {i}/{len(messages)}...")
        if send_message(msg):
            success_count += 1
        else:
            print(f"  ❌ Failed to send message {i}")

    if success_count == len(messages):
        print(f"✅ Digest sent! ({success_count} messages)")
        return True
    else:
        print(f"⚠️  Sent {success_count}/{len(messages)} messages")
        return False


def send_alert(job: dict) -> bool:
    """
    Send an instant alert for a single high-match job.
    Used when a 85%+ match is found.
    """
    score = job.get("match_score", 0)
    text  = (
        f"🚨 <b>HIGH MATCH ALERT!</b>\n\n"
        f"{format_job(job, 1)}\n\n"
        f"⚡ Apply now before it's gone!"
    )
    return send_message(text)


# ─── Entry Point ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "digest"

    if cmd == "test":
        print("Testing Telegram connection...")
        if test_connection():
            print("✅ Telegram is working!")
        else:
            print("❌ Check your TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in .env")

    elif cmd == "digest":
        jobs_path    = sys.argv[2] if len(sys.argv) > 2 else str(DEFAULT_JOBS_PATH)
        profile_path = sys.argv[3] if len(sys.argv) > 3 else str(DEFAULT_PROFILE_PATH)
        send_daily_digest(jobs_path, profile_path)

    else:
        print("Usage:")
        print("  python notifier/telegram.py test              # Test connection")
        print("  python notifier/telegram.py digest            # Send daily digest")
